# Generated by Django 5.0.6 on 2024-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
                ('CustomerLocation', models.CharField(max_length=500)),
                ('CustomerNumber', models.CharField(max_length=500)),
            ],
        ),
    ]
